FiapSchoolSystem.Client/Controllers/AlunoController.cs
using FiapSchoolSystem.Client.Contracts;
using FiapSchoolSystem.Client.Models;
using FiapSchoolSystem.Client.Models.Dto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FiapSchoolSystem.Client.Controllers;
public class AlunoController : Controller
{
	private readonly IAlunoService _alunoService;
	public AlunoController(IAlunoService alunoService)
	{
		_alunoService = alunoService;
	}

	public async Task<IActionResult> Index()
	{
		List<AlunoViewModel> list = new List<AlunoViewModel>();
		var response = await _alunoService.GetAllAlunosAsync<ResponseDto>();
		if (response != null && response.IsSuccess)
		{
			list = JsonConvert.DeserializeObject<List<AlunoViewModel>>(Convert.ToString(response.Result));
		}
		return View(list);
	}

	public async Task<IActionResult> CreateAluno()
	{
		return View();
	}

	[HttpPost]
	public async Task<IActionResult> CreateAluno(AlunoViewModel model)
	{
		if (ModelState.IsValid)
		{

			var response = await _alunoService.CreateAlunoAsync<ResponseDto>(model);
			if (response != null && response.IsSuccess)
			{
				return RedirectToAction(nameof(Index));
			}
		}
		return View(model);
	}

	public async Task<IActionResult> UpdateAluno(int id)
	{
		var response = await _alunoService.GetAlunoByIdAsync<ResponseDto>(id);
		if (response != null && response.IsSuccess)
		{
			AlunoViewModel model = JsonConvert.DeserializeObject<AlunoViewModel>(Convert.ToString(response.Result));
			return View(model);
		}
		return NotFound();
	}

	[HttpPost]
	public async Task<IActionResult> UpdateAluno(AlunoViewModel model)
	{
		if (ModelState.IsValid)
		{
			var response = await _alunoService.UpdateAlunoAsync<ResponseDto>(model.Id, model);
			if (response != null && response.IsSuccess)
			{
				return RedirectToAction(nameof(Index));
			}
		}
		return View(model);
	}

	
	public async Task<IActionResult> DeleteAluno(int id)
	{
		var response = await _alunoService.GetAlunoByIdAsync<ResponseDto>(id);
		if (response != null && response.IsSuccess)
		{
			AlunoViewModel model = JsonConvert.DeserializeObject<AlunoViewModel>(Convert.ToString(response.Result));
			return View(model);
		}
		return NotFound();
	}

	[HttpPost]
	public async Task<IActionResult> DeleteAluno(AlunoViewModel model)
	{
		var response = await _alunoService.DeleteAlunoAsync<ResponseDto>(model.Id);
		if (response.IsSuccess)
		{
			return RedirectToAction(nameof(Index));
		}
		return View(model);
	}
}

FiapSchoolSystem.Client/Controllers/AlunoTurmaController.cs
using FiapSchoolSystem.Client.Contracts;
using FiapSchoolSystem.Client.Models;
using FiapSchoolSystem.Client.Models.Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace FiapSchoolSystem.Client.Controllers;
public class AlunoTurmaController : Controller
{
    private readonly IAlunoTurmaService _alunoTurmaService;
    public AlunoTurmaController(IAlunoTurmaService alunoTurmaService)
    {
        _alunoTurmaService = alunoTurmaService;
    }

    public async Task<IActionResult> Index()
    {
        List<TurmaViewModel> list = new List<TurmaViewModel>();
        var response = await _alunoTurmaService.GetAllTurmasAsync<ResponseDto>();
        if (response != null && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<TurmaViewModel>>(Convert.ToString(response.Result));
        }
        return View(list);
    }

    public async Task<IActionResult> ListAluno(int id)
    {
        List<AlunoViewModel> list = new List<AlunoViewModel>();
        var response = await _alunoTurmaService.GetAllAlunosAsync<ResponseDto>(id);
        if (response != null && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<AlunoViewModel>>(Convert.ToString(response.Result));
        }


        return View(list);
    }

    public async Task<IActionResult> CreateRelationship()
    {
        List<TurmaViewModel> listTurma = new List<TurmaViewModel>();
        var responseTurma = await _alunoTurmaService.GetTurmasToDropListAsync<ResponseDto>();
        if (responseTurma != null && responseTurma.IsSuccess)
        {
            listTurma = JsonConvert.DeserializeObject<List<TurmaViewModel>>(Convert.ToString(responseTurma.Result));
        }

        List<AlunoViewModel> listAluno = new List<AlunoViewModel>();
        var response = await _alunoTurmaService.GetAllAlunosAsync<ResponseDto>();
        if (response != null && response.IsSuccess)
        {
            listAluno = JsonConvert.DeserializeObject<List<AlunoViewModel>>(Convert.ToString(response.Result));
        }

        var model = new AlunoTurmaViewModel
        {
            Turmas = listTurma,
            Alunos = listAluno

        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> CreateRelationship(AlunoTurmaViewModel model)
    {

        var response = await _alunoTurmaService.CreateAlunoTurmaAsync<ResponseDto>(model);
        if (response != null && response.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }

        ModelState.AddModelError("ErrorMessage", response!.ErrorMessages.First());

         model = new AlunoTurmaViewModel
        {
            Turmas = new List<TurmaViewModel> { },
            Alunos = new List<AlunoViewModel> { }

         };

        return View(model);
    }

    public async Task<IActionResult> UpdateRelationship(int id)
    {

        List<TurmaViewModel> listTurma = new List<TurmaViewModel>();
        TurmaViewModel turma = new();
        var response = await _alunoTurmaService.GetTurmaByIdAsync<ResponseDto>(id);
        if (response != null && response.IsSuccess)
        {
            turma = JsonConvert.DeserializeObject<TurmaViewModel>(Convert.ToString(response.Result));
            listTurma.Add(turma);

        }

        List<AlunoViewModel> listAluno = new List<AlunoViewModel>();
        var responseAlunos = await _alunoTurmaService.GetAllAlunosAsync<ResponseDto>();
        if (responseAlunos != null && responseAlunos.IsSuccess)
        {
            listAluno = JsonConvert.DeserializeObject<List<AlunoViewModel>>(Convert.ToString(responseAlunos.Result));

        }



        var model = new AlunoTurmaViewModel
        {
            Turmas = listTurma,
            Alunos = listAluno

        };

        return View(model);
    }


    public async Task<IActionResult> DeleteRelationship(int id, string turma_id)
    {

        var response = await _alunoTurmaService.DeleteAlunoTurmaAsync<ResponseDto>(id, turma_id);
        if (response.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }
        return View();
    }

}

FiapSchoolSystem.Client/Controllers/TumaController.cs
using FiapSchoolSystem.Client.Contracts;
using FiapSchoolSystem.Client.Models;
using FiapSchoolSystem.Client.Models.Dto;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FiapSchoolSystem.Client.Controllers;
public class TurmaController : Controller
{
    private readonly ITurmaService _turmaService;
    public TurmaController(ITurmaService turmaService)
    {
        _turmaService = turmaService;
    }

    public async Task<IActionResult> Index()
    {
        List<TurmaViewModel> list = new List<TurmaViewModel>();
        var response = await _turmaService.GetAllTurmasAsync<ResponseDto>();
        if (response != null && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<TurmaViewModel>>(Convert.ToString(response.Result));
        }
        return View(list);
    }

    public async Task<IActionResult> CreateTurma()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> CreateTurma(TurmaViewModel model)
    {
        if (ModelState.IsValid)
        {
            var response = await _turmaService.CreateTurmaAsync<ResponseDto>(model);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError("ErrorMessage", response!.ErrorMessages.First());
        }

        return View(model);
    }

    public async Task<IActionResult> UpdateTurma(int id)
    {
        var response = await _turmaService.GetTurmaByIdAsync<ResponseDto>(id);
        if (response != null && response.IsSuccess)
        {
            TurmaViewModel model = JsonConvert.DeserializeObject<TurmaViewModel>(Convert.ToString(response.Result));
            return View(model);
        }
        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> UpdateTurma(TurmaViewModel model)
    {
        if (ModelState.IsValid)
        {
            var response = await _turmaService.UpdateTurmaAsync<ResponseDto>(model.Id, model);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
        }
        return View(model);
    }

    public async Task<IActionResult> DeleteTurma(int id)
    {
        var response = await _turmaService.GetTurmaByIdAsync<ResponseDto>(id);
        if (response != null && response.IsSuccess)
        {
            TurmaViewModel model = JsonConvert.DeserializeObject<TurmaViewModel>(Convert.ToString(response.Result));
            return View(model);
        }
        return NotFound();
    }


    [HttpPost]
    public async Task<IActionResult> DeleteTurma(TurmaViewModel model)
    {
        var response = await _turmaService.DeleteTurmaAsync<ResponseDto>(model.Id);
        if (response.IsSuccess)
        {
            return RedirectToAction(nameof(Index));
        }
        return View(model);
    }
}

FiapSchoolSystem.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Fiap School System</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/FiapSchoolSystem.Client.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img width="90" height="35" alt="FIAP School System" src="/images/logoFiap.png" /></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				  <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Turma" asp-action="Index">Turmas</a>
                        </li>
						<li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="AlunoTurma" asp-action="Index">Alunos/Turmas</a>
                        </li>
                    </ul>
                </div>
				@*<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">*@
				
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted bg-dark">
		<div class="container">
			&copy; 2023 - FIAP School System
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>